In [1]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
#lists the content of your google drive
!ls "/content/drive/My Drive"

'Colab Notebooks'				      groupwork
'Data Mining - Summaries 2018 19.gdoc'		      HRI
'DDD group assignment report - Line chart 1.gsheet'  'Sample upload.txt'
'Getting started.pdf'


In [0]:
link = 'https://drive.google.com/open?id=1DPZZQ43w8brRhbEMolgLqOWKbZbE-IQu' # The shareable link

In [4]:
import numpy
import pandas as pd
written_train =  numpy.load('drive/My Drive/Colab Notebooks/written_train(1).npy', allow_pickle=True)
spoken_train = numpy.load('drive/My Drive/Colab Notebooks/spoken_train(1).npy', allow_pickle=True)
match_train =  numpy.load('drive/My Drive/Colab Notebooks/match_train(1).npy', allow_pickle=True)
feature_amount = spoken_train[0].shape[1]
print("shape written:", written_train.shape)
print("shape spoken", spoken_train.shape)
print("shape spoken indiv:", spoken_train[4].shape)
print(feature_amount)
print(match_train)

shape written: (45000, 784)
shape spoken (45000,)
shape spoken indiv: (38, 13)
13
[False False False ... False False False]


In [5]:
import pandas as pd
from numpy import array

maxs = []
for i in range(0, len(spoken_train)):
    maxs.append(spoken_train[i].shape[0])
maxlen_spoken_train = max(maxs)

from keras.preprocessing.sequence import pad_sequences

spoken_train_3d= pad_sequences(spoken_train, maxlen= max(maxs))
print(spoken_train_3d.shape)

spoken_train_2d =spoken_train_3d.reshape(45000, maxlen_spoken_train*feature_amount)

print(spoken_train_2d.shape)


Using TensorFlow backend.


(45000, 93, 13)
(45000, 1209)


In [7]:
import numpy as np

def features(signal, functions):
    res= []
    for func in functions:
        res.append(func(signal, axis=2)) #functie wordt toegepast op de derde axis wat y is 
    return np.concatenate(res, axis=1) # samenvoegen van res met 
        
#.........................................    
summaries = [np.mean, np.min, np.max, np.median, np.std]    
spoken_train_2d = features(spoken_train_3d, summaries)
print("Input shape {}".format(spoken_train_3d.shape))
print("The resulting shape should be {}".format(
        (spoken_train_3d.shape[0], spoken_train_3d.shape[1]*len(summaries))))
print(spoken_train_2d.shape)

Input shape (45000, 93, 13)
The resulting shape should be (45000, 465)
(45000, 465)


In [0]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

ss_scaler = StandardScaler()
spoken_train_mmsc = ss_scaler.fit_transform(spoken_train_2d)
written_train_mmsc = ss_scaler.fit_transform(written_train)

#until here


In [9]:
import numpy as np

def features(signal, functions):
    res= []
    for func in functions:
        res.append(func(signal, axis=2)) #functie wordt toegepast op de derde axis wat y is 
    return np.concatenate(res, axis=1) # samenvoegen van res met 
        
#.........................................    
summaries = [np.mean, np.min, np.max, np.median, np.std]    
spoken_train_2d = features(spoken_train_3d, summaries)
print("Input shape {}".format(spoken_train_3d.shape))
print("The resulting shape should be {}".format(
        (spoken_train_3d.shape[0], spoken_train_3d.shape[1]*len(summaries))))
print(spoken_train_2d.shape)

Input shape (45000, 93, 13)
The resulting shape should be (45000, 465)
(45000, 465)


In [0]:
from imblearn.over_sampling import SMOTE

print("Before OverSampling, counts of label '1': {}".format(sum(y_train==0)))
print("Before OverSampling, counts of label '2': {} ".format(sum(y_train==1)))

sm = SMOTE(random_state=666)
X_res, y_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of X: {}'.format(X_res.shape))
print('After OverSampling, the shape of y: {} \n'.format(y_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_res==0)))
print("After OverSampling, counts of label '2': {}".format(sum(y_res==1)))


X= numpy.array(X_res)
y= numpy.array(y_res)


/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


Before OverSampling, counts of label '1': 40461
Before OverSampling, counts of label '2': 4539 


In [0]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',
                                                 numpy.unique(y_train),
                                                 y_train)



In [12]:
X_train=X_resampled
y_train=y_resampled
print(y_train.shape)

NameError: ignored

In [9]:
# import labelencoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# instantiate labelencoder object
le = LabelEncoder()
y_train = le.fit_transform(y_train)
print(y_train)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = y_train.reshape(len(y_train), 1)
y_train = onehot_encoder.fit_transform(integer_encoded)
print(y_train)

[0 0 0 ... 0 0 0]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


# LSTM

In [0]:
import numpy
import matplotlib.pyplot as plt
import pandas
import math
import keras 
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [42]:
 print(X_train.shape)
X_train = X_train.reshape(X_train.shape[0],1249,1)
y_train = y_train.reshape(X_train.shape[0],2)

(45000, 1249, 1)


In [43]:
print(X_train.shape)
print(y_train.shape)

(45000, 1249, 1)
(45000, 2)


In [0]:
import numpy
import matplotlib.pyplot as plt
import pandas
import math
from sklearn.utils import class_weight

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, LSTM
#from sklearn.preprocessing import MinMaxScaler
#from sklearn.metrics import mean_squared_error

In [1]:
model_m = Sequential()
model_m.add(Conv1D(32, 10, activation='relu', input_shape=(1993, 1)))
model_m.add(MaxPooling1D(5))
model_m.add(Conv1D(80, 3, activation='relu'))
model_m.add(GlobalAveragePooling1D())
#odel_m.add(Dropout(0.2))

model_m.add(Dense(2574, input_dim=1249, activation='relu'))
model_m.add(Dropout(0.2))
model_m.add(Dense(1287, activation='relu'))
model_m.add(Dropout(0.2))
model_m.add(Dense(644, activation='relu'))
model_m.add(Dropout(0.2))
model_m.add(Dense(644, activation='relu'))
model_m.add(Dropout(0.2))
model_m.add(Dense(2, activation='softmax'))
print(model_m.summary())

NameError: ignored

In [87]:
callbacks_list = [
    keras.callbacks.ModelCheckpoint(
        filepath='best_model.{epoch:02d}-{val_loss:.2f}.h5',
        monitor='acc', save_best_only=True),
    keras.callbacks.EarlyStopping(monitor='acc', patience=1)
]

model_m.compile(loss='poisson',
                optimizer='rmsprop', metrics=['accuracy'])

BATCH_SIZE = 129
EPOCHS = 50

history = model_m.fit(X_train,
                      y_train,
                      batch_size=BATCH_SIZE,
                      epochs=40,
                      class_weight=class_weights,
                      callbacks=callbacks_list,
             
                      validation_split=0.2,
                      verbose=1)
print(history.history.keys())

Train on 36000 samples, validate on 9000 samples
Epoch 1/40
36000/36000 [==============================] - 59s 2ms/step - loss: 1.3104 - acc: 0.8971 - val_loss: 1.3193 - val_acc: 0.8983
Epoch 2/40
36000/36000 [==============================] - 58s 2ms/step - loss: 1.3113 - acc: 0.8993 - val_loss: 1.3193 - val_acc: 0.8983
Epoch 3/40
36000/36000 [==============================] - 57s 2ms/step - loss: 1.3113 - acc: 0.8993 - val_loss: 1.3193 - val_acc: 0.8983
dict_keys(['val_loss', 'val_acc', 'loss', 'acc'])


In [0]:
#LSTM model we used

from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras import layers

model = Sequential()
model.add(LSTM(1000,input_shape=(1249,1),return_sequences=False))#True = many to many
#model.add(Dense(2574, activation='relu'))
#model.add(Dropout(0.5))
#model.add(Dense(1287, activation='relu'))
#model.add(Dropout(0.5))
#model.add(Dense(644, activation='relu'))
#model.add(Dropout(0.5))
#model.add(Dense(644, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2,kernel_initializer= 'normal',activation= 'softmax'))

In [0]:
#Compile the model

model.compile(
 optimizer = "rmsprop", loss='binary_crossentropy',
 metrics = ["accuracy"])

In [0]:
model.fit(X_train, y_train, epochs= 10, batch_size = 500, validation_split=0.2) #batch_size = 8000


Instructions for updating:
Use tf.cast instead.
Train on 36000 samples, validate on 9000 samples
Epoch 1/10


# TESTEN

In [0]:
written_test =numpy.load('drive/My Drive/Colab Notebooks/written_test(1).npy', allow_pickle=True)
spoken_test =numpy.load('drive/My Drive/Colab Notebooks/spoken_test(1).npy', allow_pickle=True)

In [0]:
import pandas as pd
from numpy import array

maxs = []
for i in range(0, len(spoken_test)):
    maxs.append(spoken_test[i].shape[0])
maxlen_spoken_test = max(maxs)

from keras.preprocessing.sequence import pad_sequences

spoken_test_3d= pad_sequences(spoken_test, maxlen= max(maxs))
print(spoken_test_3d.shape)

spoken_test_2d =spoken_test_3d.reshape(15000, maxlen_spoken_test*feature_amount)

spoken_test_2d


(15000, 93, 13)


array([[ 0,  0,  0, ..., -1,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., -2,  0,  1],
       ...,
       [ 0,  0,  0, ..., -2, -1,  0],
       [ 0,  0,  0, ..., -2, -1,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=int32)

In [0]:
mm_scaler = StandardScaler()
spoken_test_mmsc = mm_scaler.fit_transform(spoken_test_2d)
written_test_mmsc = mm_scaler.fit_transform(written_test)


In [0]:
X_test = numpy.hstack([spoken_test_mmsc, written_test_mmsc])
X_test = X_test.reshape(15000,1993,1)

In [0]:
from sklearn.metrics import accuracy_score

y_pred = model_m.predict_classes(X_test, verbose=1)

print(y_pred)

print(0 in y_pred)

15000/15000 [==============================] - 13s 851us/step
[1 1 1 ... 1 1 1]
True


In [0]:
print(0 in y_pred)

True


In [0]:
numpy.save("attempt97.npy", y_pred)